name: Build and push a Docker Image

on:
  push:
  
jobs:
  build:
    name: Build and Push a Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: code recuperation
        uses: actions/checkout@v4
      
      - name: Docker configuration
        uses: docker/setup-buildx-action@v3
      
      - name: Docker connection
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push the Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/mini-projet-docker-deploy:latest
            ${{ secrets.DOCKER_USERNAME }}/mini-projet-docker-deploy:${{ github.sha }}
